# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\chams\projet\Ui_access_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FaceRec(object):
    def setupUi(self, FaceRec):
        FaceRec.setObjectName("FaceRec")
        FaceRec.resize(996, 600)
        self.centralWidget = QtWidgets.QWidget(FaceRec)
        self.centralWidget.setMinimumSize(QtCore.QSize(0, 600))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 591, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(0, 205, 591, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(0, 550, 181, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(170, 550, 20, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 591, 161))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButtonSTART = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonSTART.setObjectName("pushButtonSTART")
        self.horizontalLayout_3.addWidget(self.pushButtonSTART)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButtonSTART_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonSTART_2.setObjectName("pushButtonSTART_2")
        self.horizontalLayout_4.addWidget(self.pushButtonSTART_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_3.setObjectName("label_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_2.setGeometry(QtCore.QRect(300, 7, 291, 42))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(10, 236, 581, 301))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView_image_comparator = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_image_comparator.setGeometry(QtCore.QRect(0, 130, 576, 141))
        self.graphicsView_image_comparator.setObjectName("graphicsView_image_comparator")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 30, 281, 61))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_source_image = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_source_image.setObjectName("pushButton_source_image")
        self.horizontalLayout_5.addWidget(self.pushButton_source_image)
        self.lineEdit_source_image = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_source_image.setObjectName("lineEdit_source_image")
        self.horizontalLayout_5.addWidget(self.lineEdit_source_image)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 131, 16))
        self.label_2.setObjectName("label_2")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(0, 15, 60, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(295, 0, 282, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(0, 110, 62, 13))
        self.label_6.setObjectName("label_6")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(0, 90, 582, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_3.setGeometry(QtCore.QRect(305, 0, 271, 101))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 201, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_source_folder = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_source_folder.setObjectName("pushButton_source_folder")
        self.horizontalLayout_8.addWidget(self.pushButton_source_folder)
        self.lineEdit_source_folder = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_source_folder.setObjectName("lineEdit_source_folder")
        self.horizontalLayout_8.addWidget(self.lineEdit_source_folder)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_terminer = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_terminer.setObjectName("pushButton_terminer")
        self.horizontalLayout_9.addWidget(self.pushButton_terminer)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.treeView_liste_personne = QtWidgets.QTreeView(self.tab_2)
        self.treeView_liste_personne.setGeometry(QtCore.QRect(210, 120, 361, 155))
        self.treeView_liste_personne.setObjectName("treeView_liste_personne")
        self.tabWidget.addTab(self.tab_2, "")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(4, 218, 131, 16))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.groupBox)
        FaceRec.setCentralWidget(self.centralWidget)

        self.retranslateUi(FaceRec)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FaceRec)

    def retranslateUi(self, FaceRec):
        _translate = QtCore.QCoreApplication.translate
        FaceRec.setWindowTitle(_translate("FaceRec", "MainWindow"))
        self.groupBox.setTitle(_translate("FaceRec", "TRAITEMENT"))
        self.label_4.setText(_translate("FaceRec", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\"><br/></span></p><p align=\"center\"><span style=\" font-weight:600; color:#22535e;\">S\'AUTHENTIFIER</span></p><p align=\"center\"><span style=\" font-weight:600;\"><br/></span></p></body></html>"))
        self.pushButtonSTART.setText(_translate("FaceRec", "START"))
        self.label_5.setText(_translate("FaceRec", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-weight:600; color:#22535e;\">S\'ENREGISTRER</span></p><p align=\"center\"><br/></p></body></html>"))
        self.pushButtonSTART_2.setText(_translate("FaceRec", "START"))
        self.label_3.setText(_translate("FaceRec", "CONTROLE DIRECT"))
        self.textBrowser_2.setHtml(_translate("FaceRec", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CE METHODE CONSISTE A AUTHENTIFIER LA PERSONE,OU BIEN L\'ENREGISTRER DANS LA BASE DE DONNEE</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_source_image.setText(_translate("FaceRec", "IMAGE"))
        self.label_2.setText(_translate("FaceRec", "IMAGE PATH"))
        self.textBrowser.setHtml(_translate("FaceRec", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#0d3505;\">ASTUCE: AVANT DE PROCEDER A CETTE METHODE, IL EST FORTEMENT CONSEILLER DE REMPLIR LA BASE DE DONNEE D\'IMAGE DANS L\'ONGLET 2. ENSUITE, IL FAUT SPECIFIER L\'IMAGE TEST.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; color:#0d3505;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#0d3505;\">NB: IL SE PEUT QUE CETTE METHODE DONNE DES FAUSSES RESULTATS, CA  DEPEND DE LA QUALITE DE L\'IMAGE FOURNIE</span></p></body></html>"))
        self.label_6.setText(_translate("FaceRec", "RESULTAT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FaceRec", "Tab 1"))
        self.textBrowser_3.setHtml(_translate("FaceRec", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ASTUCE: AJOUT D\'IMAGE DANS LA BASE DE DONNEE</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">N°1: CREER UN NOUVEAU DOSSIER</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">N°2: AJOUTER LA PHOTO DE LA PERSONNE DANS CE NOUVEAU DOSSIER</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">N°3: RENNOMER LE NOUVEAU DOSSIER EN LUI DONNANT COMME NOM, LE NOM DE LA PERSONNE</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">N°4: CLICKER SUR SOURCE POUR AJOUTER LE NOUVEAU DOSSIER </p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">N°5:  CLICQUER SUR TERMINER POUR AJOUTER LA PHOTO DANS LA BASE</p></body></html>"))
        self.label_7.setText(_translate("FaceRec", "CREER UN NOUVEAU DOSSIER"))
        self.pushButton_source_folder.setText(_translate("FaceRec", "SOURCE"))
        self.pushButton_terminer.setText(_translate("FaceRec", "Terminer"))
        self.label_8.setText(_translate("FaceRec", "BASE:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("FaceRec", "Tab 2"))
        self.label.setText(_translate("FaceRec", "<html><head/><body><p align=\"center\"><span style=\" text-decoration: underline;\">RECONNAISSANCE </span><span style=\" font-size:9pt; text-decoration: underline;\">1</span><span style=\" text-decoration: underline;\">xN</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FaceRec = QtWidgets.QMainWindow()
    ui = Ui_FaceRec()
    ui.setupUi(FaceRec)
    FaceRec.show()
    sys.exit(app.exec_())
